- hosts: all
  become: yes
  tasks:
    - name: "Create dabatase"
      shell: echo "create database SpringWebYoutubeTest;"| sudo kubectl exec -it mysql-5fb6fb7fb4-vs2js --tty -- mysql -uroot -ppassword_mysql
    
    - name: "Restore dump"
      shell: cat dump_sql.sql | kubectl exec -it mysql-5fb6fb7fb4-vs2js --tty -- mysql -uroot -ppassword_mysql SpringWebYoutubeTest